### ISSUE TITLE
Fails with Pod::Simple 3.30

### ISSUE THREAD

**Issue by andk** [argrath/Pod-L10N#2]
As per subject. Sample fail report:

http://www.cpantesters.org/cpan/report/51910541

HTH&&Thanks,
(Disclaimer: this was discovered by statistical analysis, I'm not speaking as a user)

**Comment by andk** [comment]
https://rt.cpan.org/Ticket/Display.html?id=102368 is a cross referencing ticket against Pod::Simple

**Comment by theory** [comment]
Thanks. I fixed the warning in [37e1a25](/theory/pod-simple/commit/37e1a25) and now your tests pass again.

**Comment by argrath** [comment]
Thanks.  As released Pod::Simple 3.31, close this issue.
